# Generated by Django 4.2.1 on 2023-05-04 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(max_length=1)),
                ('height', models.FloatField(max_length=3)),
                ('starting_weight', models.FloatField(max_length=6)),
                ('aerobics', models.BooleanField(default=False)),
                ('recent_weight', models.FloatField(max_length=6)),
                ('public_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('new_weight', models.FloatField(max_length=6)),
                ('observations', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
